# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/runner/work/otus_homework_9/otus_homework_9

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/runner/work/otus_homework_9/otus_homework_9

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool..."
	cd /home/runner/work/otus_homework_9/otus_homework_9 && /usr/local/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package
.PHONY : package/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool for source..."
	cd /home/runner/work/otus_homework_9/otus_homework_9 && /usr/local/bin/cpack --config ./CPackSourceConfig.cmake /home/runner/work/otus_homework_9/otus_homework_9/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source
.PHONY : package_source/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/local/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	cd /home/runner/work/otus_homework_9/otus_homework_9 && $(CMAKE_COMMAND) -E cmake_progress_start /home/runner/work/otus_homework_9/otus_homework_9/CMakeFiles /home/runner/work/otus_homework_9/otus_homework_9/src_lib//CMakeFiles/progress.marks
	cd /home/runner/work/otus_homework_9/otus_homework_9 && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 src_lib/all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/runner/work/otus_homework_9/otus_homework_9/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	cd /home/runner/work/otus_homework_9/otus_homework_9 && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 src_lib/clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	cd /home/runner/work/otus_homework_9/otus_homework_9 && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 src_lib/preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	cd /home/runner/work/otus_homework_9/otus_homework_9 && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 src_lib/preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	cd /home/runner/work/otus_homework_9/otus_homework_9 && $(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

# Convenience name for target.
src_lib/CMakeFiles/doc_doxygen.dir/rule:
	cd /home/runner/work/otus_homework_9/otus_homework_9 && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 src_lib/CMakeFiles/doc_doxygen.dir/rule
.PHONY : src_lib/CMakeFiles/doc_doxygen.dir/rule

# Convenience name for target.
doc_doxygen: src_lib/CMakeFiles/doc_doxygen.dir/rule
.PHONY : doc_doxygen

# fast build rule for target.
doc_doxygen/fast:
	cd /home/runner/work/otus_homework_9/otus_homework_9 && $(MAKE) $(MAKESILENT) -f src_lib/CMakeFiles/doc_doxygen.dir/build.make src_lib/CMakeFiles/doc_doxygen.dir/build
.PHONY : doc_doxygen/fast

# Convenience name for target.
src_lib/CMakeFiles/async.dir/rule:
	cd /home/runner/work/otus_homework_9/otus_homework_9 && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 src_lib/CMakeFiles/async.dir/rule
.PHONY : src_lib/CMakeFiles/async.dir/rule

# Convenience name for target.
async: src_lib/CMakeFiles/async.dir/rule
.PHONY : async

# fast build rule for target.
async/fast:
	cd /home/runner/work/otus_homework_9/otus_homework_9 && $(MAKE) $(MAKESILENT) -f src_lib/CMakeFiles/async.dir/build.make src_lib/CMakeFiles/async.dir/build
.PHONY : async/fast

# Convenience name for target.
src_lib/CMakeFiles/version_lib.dir/rule:
	cd /home/runner/work/otus_homework_9/otus_homework_9 && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 src_lib/CMakeFiles/version_lib.dir/rule
.PHONY : src_lib/CMakeFiles/version_lib.dir/rule

# Convenience name for target.
version_lib: src_lib/CMakeFiles/version_lib.dir/rule
.PHONY : version_lib

# fast build rule for target.
version_lib/fast:
	cd /home/runner/work/otus_homework_9/otus_homework_9 && $(MAKE) $(MAKESILENT) -f src_lib/CMakeFiles/version_lib.dir/build.make src_lib/CMakeFiles/version_lib.dir/build
.PHONY : version_lib/fast

# Convenience name for target.
src_lib/CMakeFiles/test_Version.dir/rule:
	cd /home/runner/work/otus_homework_9/otus_homework_9 && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 src_lib/CMakeFiles/test_Version.dir/rule
.PHONY : src_lib/CMakeFiles/test_Version.dir/rule

# Convenience name for target.
test_Version: src_lib/CMakeFiles/test_Version.dir/rule
.PHONY : test_Version

# fast build rule for target.
test_Version/fast:
	cd /home/runner/work/otus_homework_9/otus_homework_9 && $(MAKE) $(MAKESILENT) -f src_lib/CMakeFiles/test_Version.dir/build.make src_lib/CMakeFiles/test_Version.dir/build
.PHONY : test_Version/fast

# Convenience name for target.
src_lib/CMakeFiles/test_ICommand.dir/rule:
	cd /home/runner/work/otus_homework_9/otus_homework_9 && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 src_lib/CMakeFiles/test_ICommand.dir/rule
.PHONY : src_lib/CMakeFiles/test_ICommand.dir/rule

# Convenience name for target.
test_ICommand: src_lib/CMakeFiles/test_ICommand.dir/rule
.PHONY : test_ICommand

# fast build rule for target.
test_ICommand/fast:
	cd /home/runner/work/otus_homework_9/otus_homework_9 && $(MAKE) $(MAKESILENT) -f src_lib/CMakeFiles/test_ICommand.dir/build.make src_lib/CMakeFiles/test_ICommand.dir/build
.PHONY : test_ICommand/fast

# Convenience name for target.
src_lib/CMakeFiles/test_ICommandQueue.dir/rule:
	cd /home/runner/work/otus_homework_9/otus_homework_9 && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 src_lib/CMakeFiles/test_ICommandQueue.dir/rule
.PHONY : src_lib/CMakeFiles/test_ICommandQueue.dir/rule

# Convenience name for target.
test_ICommandQueue: src_lib/CMakeFiles/test_ICommandQueue.dir/rule
.PHONY : test_ICommandQueue

# fast build rule for target.
test_ICommandQueue/fast:
	cd /home/runner/work/otus_homework_9/otus_homework_9 && $(MAKE) $(MAKESILENT) -f src_lib/CMakeFiles/test_ICommandQueue.dir/build.make src_lib/CMakeFiles/test_ICommandQueue.dir/build
.PHONY : test_ICommandQueue/fast

_tests/test_ICommand.o: _tests/test_ICommand.cpp.o
.PHONY : _tests/test_ICommand.o

# target to build an object file
_tests/test_ICommand.cpp.o:
	cd /home/runner/work/otus_homework_9/otus_homework_9 && $(MAKE) $(MAKESILENT) -f src_lib/CMakeFiles/test_ICommand.dir/build.make src_lib/CMakeFiles/test_ICommand.dir/_tests/test_ICommand.cpp.o
.PHONY : _tests/test_ICommand.cpp.o

_tests/test_ICommand.i: _tests/test_ICommand.cpp.i
.PHONY : _tests/test_ICommand.i

# target to preprocess a source file
_tests/test_ICommand.cpp.i:
	cd /home/runner/work/otus_homework_9/otus_homework_9 && $(MAKE) $(MAKESILENT) -f src_lib/CMakeFiles/test_ICommand.dir/build.make src_lib/CMakeFiles/test_ICommand.dir/_tests/test_ICommand.cpp.i
.PHONY : _tests/test_ICommand.cpp.i

_tests/test_ICommand.s: _tests/test_ICommand.cpp.s
.PHONY : _tests/test_ICommand.s

# target to generate assembly for a file
_tests/test_ICommand.cpp.s:
	cd /home/runner/work/otus_homework_9/otus_homework_9 && $(MAKE) $(MAKESILENT) -f src_lib/CMakeFiles/test_ICommand.dir/build.make src_lib/CMakeFiles/test_ICommand.dir/_tests/test_ICommand.cpp.s
.PHONY : _tests/test_ICommand.cpp.s

_tests/test_ICommandQueue.o: _tests/test_ICommandQueue.cpp.o
.PHONY : _tests/test_ICommandQueue.o

# target to build an object file
_tests/test_ICommandQueue.cpp.o:
	cd /home/runner/work/otus_homework_9/otus_homework_9 && $(MAKE) $(MAKESILENT) -f src_lib/CMakeFiles/test_ICommandQueue.dir/build.make src_lib/CMakeFiles/test_ICommandQueue.dir/_tests/test_ICommandQueue.cpp.o
.PHONY : _tests/test_ICommandQueue.cpp.o

_tests/test_ICommandQueue.i: _tests/test_ICommandQueue.cpp.i
.PHONY : _tests/test_ICommandQueue.i

# target to preprocess a source file
_tests/test_ICommandQueue.cpp.i:
	cd /home/runner/work/otus_homework_9/otus_homework_9 && $(MAKE) $(MAKESILENT) -f src_lib/CMakeFiles/test_ICommandQueue.dir/build.make src_lib/CMakeFiles/test_ICommandQueue.dir/_tests/test_ICommandQueue.cpp.i
.PHONY : _tests/test_ICommandQueue.cpp.i

_tests/test_ICommandQueue.s: _tests/test_ICommandQueue.cpp.s
.PHONY : _tests/test_ICommandQueue.s

# target to generate assembly for a file
_tests/test_ICommandQueue.cpp.s:
	cd /home/runner/work/otus_homework_9/otus_homework_9 && $(MAKE) $(MAKESILENT) -f src_lib/CMakeFiles/test_ICommandQueue.dir/build.make src_lib/CMakeFiles/test_ICommandQueue.dir/_tests/test_ICommandQueue.cpp.s
.PHONY : _tests/test_ICommandQueue.cpp.s

async.o: async.cpp.o
.PHONY : async.o

# target to build an object file
async.cpp.o:
	cd /home/runner/work/otus_homework_9/otus_homework_9 && $(MAKE) $(MAKESILENT) -f src_lib/CMakeFiles/async.dir/build.make src_lib/CMakeFiles/async.dir/async.cpp.o
.PHONY : async.cpp.o

async.i: async.cpp.i
.PHONY : async.i

# target to preprocess a source file
async.cpp.i:
	cd /home/runner/work/otus_homework_9/otus_homework_9 && $(MAKE) $(MAKESILENT) -f src_lib/CMakeFiles/async.dir/build.make src_lib/CMakeFiles/async.dir/async.cpp.i
.PHONY : async.cpp.i

async.s: async.cpp.s
.PHONY : async.s

# target to generate assembly for a file
async.cpp.s:
	cd /home/runner/work/otus_homework_9/otus_homework_9 && $(MAKE) $(MAKESILENT) -f src_lib/CMakeFiles/async.dir/build.make src_lib/CMakeFiles/async.dir/async.cpp.s
.PHONY : async.cpp.s

bulk.o: bulk.cpp.o
.PHONY : bulk.o

# target to build an object file
bulk.cpp.o:
	cd /home/runner/work/otus_homework_9/otus_homework_9 && $(MAKE) $(MAKESILENT) -f src_lib/CMakeFiles/async.dir/build.make src_lib/CMakeFiles/async.dir/bulk.cpp.o
.PHONY : bulk.cpp.o

bulk.i: bulk.cpp.i
.PHONY : bulk.i

# target to preprocess a source file
bulk.cpp.i:
	cd /home/runner/work/otus_homework_9/otus_homework_9 && $(MAKE) $(MAKESILENT) -f src_lib/CMakeFiles/async.dir/build.make src_lib/CMakeFiles/async.dir/bulk.cpp.i
.PHONY : bulk.cpp.i

bulk.s: bulk.cpp.s
.PHONY : bulk.s

# target to generate assembly for a file
bulk.cpp.s:
	cd /home/runner/work/otus_homework_9/otus_homework_9 && $(MAKE) $(MAKESILENT) -f src_lib/CMakeFiles/async.dir/build.make src_lib/CMakeFiles/async.dir/bulk.cpp.s
.PHONY : bulk.cpp.s

command/Cmd.o: command/Cmd.cpp.o
.PHONY : command/Cmd.o

# target to build an object file
command/Cmd.cpp.o:
	cd /home/runner/work/otus_homework_9/otus_homework_9 && $(MAKE) $(MAKESILENT) -f src_lib/CMakeFiles/async.dir/build.make src_lib/CMakeFiles/async.dir/command/Cmd.cpp.o
	cd /home/runner/work/otus_homework_9/otus_homework_9 && $(MAKE) $(MAKESILENT) -f src_lib/CMakeFiles/test_ICommand.dir/build.make src_lib/CMakeFiles/test_ICommand.dir/command/Cmd.cpp.o
	cd /home/runner/work/otus_homework_9/otus_homework_9 && $(MAKE) $(MAKESILENT) -f src_lib/CMakeFiles/test_ICommandQueue.dir/build.make src_lib/CMakeFiles/test_ICommandQueue.dir/command/Cmd.cpp.o
.PHONY : command/Cmd.cpp.o

command/Cmd.i: command/Cmd.cpp.i
.PHONY : command/Cmd.i

# target to preprocess a source file
command/Cmd.cpp.i:
	cd /home/runner/work/otus_homework_9/otus_homework_9 && $(MAKE) $(MAKESILENT) -f src_lib/CMakeFiles/async.dir/build.make src_lib/CMakeFiles/async.dir/command/Cmd.cpp.i
	cd /home/runner/work/otus_homework_9/otus_homework_9 && $(MAKE) $(MAKESILENT) -f src_lib/CMakeFiles/test_ICommand.dir/build.make src_lib/CMakeFiles/test_ICommand.dir/command/Cmd.cpp.i
	cd /home/runner/work/otus_homework_9/otus_homework_9 && $(MAKE) $(MAKESILENT) -f src_lib/CMakeFiles/test_ICommandQueue.dir/build.make src_lib/CMakeFiles/test_ICommandQueue.dir/command/Cmd.cpp.i
.PHONY : command/Cmd.cpp.i

command/Cmd.s: command/Cmd.cpp.s
.PHONY : command/Cmd.s

# target to generate assembly for a file
command/Cmd.cpp.s:
	cd /home/runner/work/otus_homework_9/otus_homework_9 && $(MAKE) $(MAKESILENT) -f src_lib/CMakeFiles/async.dir/build.make src_lib/CMakeFiles/async.dir/command/Cmd.cpp.s
	cd /home/runner/work/otus_homework_9/otus_homework_9 && $(MAKE) $(MAKESILENT) -f src_lib/CMakeFiles/test_ICommand.dir/build.make src_lib/CMakeFiles/test_ICommand.dir/command/Cmd.cpp.s
	cd /home/runner/work/otus_homework_9/otus_homework_9 && $(MAKE) $(MAKESILENT) -f src_lib/CMakeFiles/test_ICommandQueue.dir/build.make src_lib/CMakeFiles/test_ICommandQueue.dir/command/Cmd.cpp.s
.PHONY : command/Cmd.cpp.s

command/MacroCmd.o: command/MacroCmd.cpp.o
.PHONY : command/MacroCmd.o

# target to build an object file
command/MacroCmd.cpp.o:
	cd /home/runner/work/otus_homework_9/otus_homework_9 && $(MAKE) $(MAKESILENT) -f src_lib/CMakeFiles/async.dir/build.make src_lib/CMakeFiles/async.dir/command/MacroCmd.cpp.o
	cd /home/runner/work/otus_homework_9/otus_homework_9 && $(MAKE) $(MAKESILENT) -f src_lib/CMakeFiles/test_ICommand.dir/build.make src_lib/CMakeFiles/test_ICommand.dir/command/MacroCmd.cpp.o
	cd /home/runner/work/otus_homework_9/otus_homework_9 && $(MAKE) $(MAKESILENT) -f src_lib/CMakeFiles/test_ICommandQueue.dir/build.make src_lib/CMakeFiles/test_ICommandQueue.dir/command/MacroCmd.cpp.o
.PHONY : command/MacroCmd.cpp.o

command/MacroCmd.i: command/MacroCmd.cpp.i
.PHONY : command/MacroCmd.i

# target to preprocess a source file
command/MacroCmd.cpp.i:
	cd /home/runner/work/otus_homework_9/otus_homework_9 && $(MAKE) $(MAKESILENT) -f src_lib/CMakeFiles/async.dir/build.make src_lib/CMakeFiles/async.dir/command/MacroCmd.cpp.i
	cd /home/runner/work/otus_homework_9/otus_homework_9 && $(MAKE) $(MAKESILENT) -f src_lib/CMakeFiles/test_ICommand.dir/build.make src_lib/CMakeFiles/test_ICommand.dir/command/MacroCmd.cpp.i
	cd /home/runner/work/otus_homework_9/otus_homework_9 && $(MAKE) $(MAKESILENT) -f src_lib/CMakeFiles/test_ICommandQueue.dir/build.make src_lib/CMakeFiles/test_ICommandQueue.dir/command/MacroCmd.cpp.i
.PHONY : command/MacroCmd.cpp.i

command/MacroCmd.s: command/MacroCmd.cpp.s
.PHONY : command/MacroCmd.s

# target to generate assembly for a file
command/MacroCmd.cpp.s:
	cd /home/runner/work/otus_homework_9/otus_homework_9 && $(MAKE) $(MAKESILENT) -f src_lib/CMakeFiles/async.dir/build.make src_lib/CMakeFiles/async.dir/command/MacroCmd.cpp.s
	cd /home/runner/work/otus_homework_9/otus_homework_9 && $(MAKE) $(MAKESILENT) -f src_lib/CMakeFiles/test_ICommand.dir/build.make src_lib/CMakeFiles/test_ICommand.dir/command/MacroCmd.cpp.s
	cd /home/runner/work/otus_homework_9/otus_homework_9 && $(MAKE) $(MAKESILENT) -f src_lib/CMakeFiles/test_ICommandQueue.dir/build.make src_lib/CMakeFiles/test_ICommandQueue.dir/command/MacroCmd.cpp.s
.PHONY : command/MacroCmd.cpp.s

command_queue/CmdQueue.o: command_queue/CmdQueue.cpp.o
.PHONY : command_queue/CmdQueue.o

# target to build an object file
command_queue/CmdQueue.cpp.o:
	cd /home/runner/work/otus_homework_9/otus_homework_9 && $(MAKE) $(MAKESILENT) -f src_lib/CMakeFiles/async.dir/build.make src_lib/CMakeFiles/async.dir/command_queue/CmdQueue.cpp.o
	cd /home/runner/work/otus_homework_9/otus_homework_9 && $(MAKE) $(MAKESILENT) -f src_lib/CMakeFiles/test_ICommandQueue.dir/build.make src_lib/CMakeFiles/test_ICommandQueue.dir/command_queue/CmdQueue.cpp.o
.PHONY : command_queue/CmdQueue.cpp.o

command_queue/CmdQueue.i: command_queue/CmdQueue.cpp.i
.PHONY : command_queue/CmdQueue.i

# target to preprocess a source file
command_queue/CmdQueue.cpp.i:
	cd /home/runner/work/otus_homework_9/otus_homework_9 && $(MAKE) $(MAKESILENT) -f src_lib/CMakeFiles/async.dir/build.make src_lib/CMakeFiles/async.dir/command_queue/CmdQueue.cpp.i
	cd /home/runner/work/otus_homework_9/otus_homework_9 && $(MAKE) $(MAKESILENT) -f src_lib/CMakeFiles/test_ICommandQueue.dir/build.make src_lib/CMakeFiles/test_ICommandQueue.dir/command_queue/CmdQueue.cpp.i
.PHONY : command_queue/CmdQueue.cpp.i

command_queue/CmdQueue.s: command_queue/CmdQueue.cpp.s
.PHONY : command_queue/CmdQueue.s

# target to generate assembly for a file
command_queue/CmdQueue.cpp.s:
	cd /home/runner/work/otus_homework_9/otus_homework_9 && $(MAKE) $(MAKESILENT) -f src_lib/CMakeFiles/async.dir/build.make src_lib/CMakeFiles/async.dir/command_queue/CmdQueue.cpp.s
	cd /home/runner/work/otus_homework_9/otus_homework_9 && $(MAKE) $(MAKESILENT) -f src_lib/CMakeFiles/test_ICommandQueue.dir/build.make src_lib/CMakeFiles/test_ICommandQueue.dir/command_queue/CmdQueue.cpp.s
.PHONY : command_queue/CmdQueue.cpp.s

logger/ConsoleLogger.o: logger/ConsoleLogger.cpp.o
.PHONY : logger/ConsoleLogger.o

# target to build an object file
logger/ConsoleLogger.cpp.o:
	cd /home/runner/work/otus_homework_9/otus_homework_9 && $(MAKE) $(MAKESILENT) -f src_lib/CMakeFiles/async.dir/build.make src_lib/CMakeFiles/async.dir/logger/ConsoleLogger.cpp.o
.PHONY : logger/ConsoleLogger.cpp.o

logger/ConsoleLogger.i: logger/ConsoleLogger.cpp.i
.PHONY : logger/ConsoleLogger.i

# target to preprocess a source file
logger/ConsoleLogger.cpp.i:
	cd /home/runner/work/otus_homework_9/otus_homework_9 && $(MAKE) $(MAKESILENT) -f src_lib/CMakeFiles/async.dir/build.make src_lib/CMakeFiles/async.dir/logger/ConsoleLogger.cpp.i
.PHONY : logger/ConsoleLogger.cpp.i

logger/ConsoleLogger.s: logger/ConsoleLogger.cpp.s
.PHONY : logger/ConsoleLogger.s

# target to generate assembly for a file
logger/ConsoleLogger.cpp.s:
	cd /home/runner/work/otus_homework_9/otus_homework_9 && $(MAKE) $(MAKESILENT) -f src_lib/CMakeFiles/async.dir/build.make src_lib/CMakeFiles/async.dir/logger/ConsoleLogger.cpp.s
.PHONY : logger/ConsoleLogger.cpp.s

logger/FileLogger.o: logger/FileLogger.cpp.o
.PHONY : logger/FileLogger.o

# target to build an object file
logger/FileLogger.cpp.o:
	cd /home/runner/work/otus_homework_9/otus_homework_9 && $(MAKE) $(MAKESILENT) -f src_lib/CMakeFiles/async.dir/build.make src_lib/CMakeFiles/async.dir/logger/FileLogger.cpp.o
.PHONY : logger/FileLogger.cpp.o

logger/FileLogger.i: logger/FileLogger.cpp.i
.PHONY : logger/FileLogger.i

# target to preprocess a source file
logger/FileLogger.cpp.i:
	cd /home/runner/work/otus_homework_9/otus_homework_9 && $(MAKE) $(MAKESILENT) -f src_lib/CMakeFiles/async.dir/build.make src_lib/CMakeFiles/async.dir/logger/FileLogger.cpp.i
.PHONY : logger/FileLogger.cpp.i

logger/FileLogger.s: logger/FileLogger.cpp.s
.PHONY : logger/FileLogger.s

# target to generate assembly for a file
logger/FileLogger.cpp.s:
	cd /home/runner/work/otus_homework_9/otus_homework_9 && $(MAKE) $(MAKESILENT) -f src_lib/CMakeFiles/async.dir/build.make src_lib/CMakeFiles/async.dir/logger/FileLogger.cpp.s
.PHONY : logger/FileLogger.cpp.s

version/test_Version.o: version/test_Version.cpp.o
.PHONY : version/test_Version.o

# target to build an object file
version/test_Version.cpp.o:
	cd /home/runner/work/otus_homework_9/otus_homework_9 && $(MAKE) $(MAKESILENT) -f src_lib/CMakeFiles/test_Version.dir/build.make src_lib/CMakeFiles/test_Version.dir/version/test_Version.cpp.o
.PHONY : version/test_Version.cpp.o

version/test_Version.i: version/test_Version.cpp.i
.PHONY : version/test_Version.i

# target to preprocess a source file
version/test_Version.cpp.i:
	cd /home/runner/work/otus_homework_9/otus_homework_9 && $(MAKE) $(MAKESILENT) -f src_lib/CMakeFiles/test_Version.dir/build.make src_lib/CMakeFiles/test_Version.dir/version/test_Version.cpp.i
.PHONY : version/test_Version.cpp.i

version/test_Version.s: version/test_Version.cpp.s
.PHONY : version/test_Version.s

# target to generate assembly for a file
version/test_Version.cpp.s:
	cd /home/runner/work/otus_homework_9/otus_homework_9 && $(MAKE) $(MAKESILENT) -f src_lib/CMakeFiles/test_Version.dir/build.make src_lib/CMakeFiles/test_Version.dir/version/test_Version.cpp.s
.PHONY : version/test_Version.cpp.s

version/versionLib.o: version/versionLib.cpp.o
.PHONY : version/versionLib.o

# target to build an object file
version/versionLib.cpp.o:
	cd /home/runner/work/otus_homework_9/otus_homework_9 && $(MAKE) $(MAKESILENT) -f src_lib/CMakeFiles/version_lib.dir/build.make src_lib/CMakeFiles/version_lib.dir/version/versionLib.cpp.o
.PHONY : version/versionLib.cpp.o

version/versionLib.i: version/versionLib.cpp.i
.PHONY : version/versionLib.i

# target to preprocess a source file
version/versionLib.cpp.i:
	cd /home/runner/work/otus_homework_9/otus_homework_9 && $(MAKE) $(MAKESILENT) -f src_lib/CMakeFiles/version_lib.dir/build.make src_lib/CMakeFiles/version_lib.dir/version/versionLib.cpp.i
.PHONY : version/versionLib.cpp.i

version/versionLib.s: version/versionLib.cpp.s
.PHONY : version/versionLib.s

# target to generate assembly for a file
version/versionLib.cpp.s:
	cd /home/runner/work/otus_homework_9/otus_homework_9 && $(MAKE) $(MAKESILENT) -f src_lib/CMakeFiles/version_lib.dir/build.make src_lib/CMakeFiles/version_lib.dir/version/versionLib.cpp.s
.PHONY : version/versionLib.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... package"
	@echo "... package_source"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... doc_doxygen"
	@echo "... async"
	@echo "... test_ICommand"
	@echo "... test_ICommandQueue"
	@echo "... test_Version"
	@echo "... version_lib"
	@echo "... _tests/test_ICommand.o"
	@echo "... _tests/test_ICommand.i"
	@echo "... _tests/test_ICommand.s"
	@echo "... _tests/test_ICommandQueue.o"
	@echo "... _tests/test_ICommandQueue.i"
	@echo "... _tests/test_ICommandQueue.s"
	@echo "... async.o"
	@echo "... async.i"
	@echo "... async.s"
	@echo "... bulk.o"
	@echo "... bulk.i"
	@echo "... bulk.s"
	@echo "... command/Cmd.o"
	@echo "... command/Cmd.i"
	@echo "... command/Cmd.s"
	@echo "... command/MacroCmd.o"
	@echo "... command/MacroCmd.i"
	@echo "... command/MacroCmd.s"
	@echo "... command_queue/CmdQueue.o"
	@echo "... command_queue/CmdQueue.i"
	@echo "... command_queue/CmdQueue.s"
	@echo "... logger/ConsoleLogger.o"
	@echo "... logger/ConsoleLogger.i"
	@echo "... logger/ConsoleLogger.s"
	@echo "... logger/FileLogger.o"
	@echo "... logger/FileLogger.i"
	@echo "... logger/FileLogger.s"
	@echo "... version/test_Version.o"
	@echo "... version/test_Version.i"
	@echo "... version/test_Version.s"
	@echo "... version/versionLib.o"
	@echo "... version/versionLib.i"
	@echo "... version/versionLib.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	cd /home/runner/work/otus_homework_9/otus_homework_9 && $(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

